#Eureka configuration
eureka_server: http://localhost:8761/eureka/,http://localhost:8762/eureka/

#Mongodb configuration
mongodb_host: localhost

# Kafka Configuration
bootstrap_servers: localhost:9092

#Zipkin configuration
zipkin_server_url: http://localhost:9411/
