#Eureka configuration
eureka_server: http://localhost:8761/eureka/,http://localhost:8762/eureka/
allow_bean_definition_overriding: true

#Mongodb configuration
mongodb_host: localhost
mongodb_port: 27017

# Kafka Configuration
bootstrap_servers: localhost:9092
auto_offset_reset: earliest
key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
value_deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
key_serializer: org.apache.kafka.common.serialization.StringSerializer
value_serializer: org.springframework.kafka.support.serializer.JsonSerializer
trusted_packages: *
